spring:
  application:
    name: park-api

  web:
    locale: pt-BR
    locale-resolver: fixed

  datasource:
    url: jdbc:mysql://localhost:1573/park?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: developer
    password: 03d49M$22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

server:
  port: 8082